<a href="https://colab.research.google.com/github/Marcin19721205/MachineLearningBootCamp/blob/main/06_gradient_descent01MJ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Przygotowanie danych](#2)
4. [Losowa inicjalizacja parametrów](#3)
5. [Metoda gradientu prostego](#4)
6. [Wizualizacja dopasowania](#5)



### <a name='0'></a> Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

### <a name='1'></a> Wygenerowanie danych

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


### <a name='2'></a> Przygotowanie danych

Transpozycja danych opisujących na wektor

In [3]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


dodanie wektora jednostkowego - patrz poprzednie cwiczenie

In [4]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


połączenie

In [5]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


### <a name='3'></a> Losowa inicjalizacja parametrów

In [29]:
eta = 0.01 #wskaznik uczenia (mnożnik dla gradientu)

weights = np.random.randn(2, 1) #losowo incjujemy wagi
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.2088636 ]
 [-1.95967012]]


### <a name='4'></a> Metoda gradientu prostego

In [30]:
intercept = [] #lista 1
coef = [] #lista 2

for i in range(3000): #3000 iteracji for
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y) #liczymy gradient
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

print(weights)

[[2749.95601115]
 [ 250.01027489]]


In [31]:
df = pd.DataFrame(data={'intercept': intercept, 'coef': coef})
df.head()

intercept        coef
0   72.841863  266.953476
1  125.198283  449.211991
2  163.749478  572.520474
3  192.898055  655.726800
4  215.639218  711.653474

### <a name='5'></a> Wizualizacja dopasowania

In [32]:
px.line(df, y='intercept', width=800, title='Dopasowanie: intercept')

In [33]:
px.line(df, y='coef', width=800, title='Dopasowanie: coef')